### ISSUE TITLE
debug log level does not obey logger.requestFields

### ISSUE THREAD

**Issue by drumfreak** [tsedio/logger#148]
## Informations

| Type                     |  Version |
| ------------------------ | -------- |
| Improvement | 2.x      |

---

## Description

Logger by default is set to log level 'debug' which logs all headers including Authorization Bearer tokens.  In some cases developers use environment variables to set LOG_LEVEL per environment.  This poses a risk of environment variable injection to set log levels to debug or trace and outputting these headers with authorization headers to the logs or various other output mechanisms.  

## Todos

Enable @tsed/core and @tsed/logger to obey `requestFields` in higher log levels (debug, trace, etc) to specify not logging headers:

`@Configuration({
  logger: {
    level: 'debug',
    requestFields: ["reqId", "method", "url", "body", "query", "params", "duration"]
  }
})`

**Comment by Romakita** [comment]
Hello @drumfreak 
Your issue is not at the right place. It concern the tsed repository. Also, isn’t really clear, the server logger isn’t in debug mode by default.

you can change the displayed data by overriding the PlatformLogMiddleware. For me isn’t an issue. In our context, headers is logged to reproduce call. The log are not accessible for external people.

can you reopen the issue in the right repo and clarify the description please.

see you
Romain
